# include:
#   - path: ./submodules/signoz/deploy/docker/clickhouse-setup/docker-compose.yaml
#     project_directory: ./submodules/signoz/deploy

services:
  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 55432:5432
  # app:
